DROP DATABASE IF EXISTS nova_shop;

CREATE DATABASE nova_shop;

USE nova_shop;

DROP TABLE IF EXISTS Addresses;

DROP TABLE IF EXISTS Clients;

DROP TABLE IF EXISTS Products;

DROP TABLE IF EXISTS Suppliers;

DROP TABLE IF EXISTS Orders;

DROP TABLE IF EXISTS Shops;

DROP TABLE IF EXISTS Departments;

-- MAKE TABLES
CREATE TABLE Addresses (
    id INT NOT NULL AUTO_INCREMENT,
    street VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    tk VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Clients (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    address_id int NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES Addresses(id)
);