DROP TABLE IF EXISTS Clients;

DROP TABLE IF EXISTS Addresses;

DROP TABLE IF EXISTS Suppliers;

DROP TABLE IF EXISTS Products;

DROP TABLE IF EXISTS Orders;

DROP TABLE IF EXISTS Shops;

DROP TABLE IF EXISTS Departments;